---
title: "Deliverable_1"
author: "Adler Kang"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  markdown: 
    wrap: 256
---

#install packages for analysis 
installed.packages("rio") 
installed.packages("ggplot2") 
installed.packages("DescTools") 
install.packages("dplyr")

install_formats()

rm(list = ls())

library(rio) library(ggplot2) library(DescTools) library(dplyr)

link='<https://github.com/superadlerrrk/543/blob/main/Deliverable1/Crime_Data.csv?raw=true>' 

crime = import(link)

names(crime)
head(crime\$"Primary Offense Description",30)

# check which columns contain null values

cols_with_nulls <- colSums(is.na(crime))

# print the column names with null values

names(crime)[cols_with_nulls > 0]

any(is.na(crime$"Reported Time")) 
any(is.na(crime$"Occurred Time"))
sum(is.na(crime$"Reported Time")) 
sum(is.na(crime$"Occurred Time"))

# create a logical vector indicating which rows have complete data in my_column

complete_rows <- complete.cases(crime$"Reported Time") 
complete_rows <- complete.cases(crime$"Occurred Time") 
# subset the data frame to remove rows with null values in my_column 
crime \<- crime[complete_rows, ]

sum(is.na(crime$"Reported Time")) 
sum(is.na(crime$"Occurred Time"))

crime <- crime %>% 
mutate(Precinct = if_else(Precinct == "","UNKNOWN", Precinct))

crime_grouped <- crime %>% 
group_by(Precinct, Neighborhood) %>% summarise(n = n())

crime_totals <- crime_grouped %>% 
group_by(Precinct) %>% 
summarise(total_entries = sum(n))

crime_grouped <- crime_grouped %>% 
left_join(crime_totals, by = "Precinct") %>% 
mutate(ratio = n / total_entries)

precincts <- unique(crime_grouped$Precinct)

for (precinct in precincts) { 
  data <- filter(crime_grouped, Precinct == precinct) 
  plot_title <- paste0(precinct, " Crime Entries by Neighborhood")

pie_chart <- ggplot(data, aes(x="", y=ratio, fill=Neighborhood)) +                geom_bar(stat="identity", width=1) + coord_polar("y", start=0) +
  labs(title=plot_title) + theme_void()
  print(pie_chart) }

crime$grouped_time <- cut(crime$"Occurred Time", 
  breaks = c(0, 1, 559, 1159, 1759, 2359), 
  labels = c("Unknown", "Midnight", "Morning", "Afternoon", "Evening"),
  include.lowest = TRUE)

table(crime$Precinct, crime$grouped_time)

